use day9_macro_demo::*;

// The procedural macro will generate a new struct definition with specified fields and methods
#[foo_bar_attribute]
struct MyStruct {
    baz: i32,
}

#[destroy_attribute]
struct MyStruct2 {
    baz: i32,
    qux: i32,
}

// The derive attribute “augmented” Foo in such a way that println! could create a string representation for it.
#[derive(Debug)]
struct Foo {
    bar: i32,
}

fn main() {
    // Create a new instance of `MyStruct` using the `default()` method
    // This method is provided by the `Default` trait implementation generated by the macro
    let demo = MyStruct::default();

    // Print the contents of `demo` to the console
    // The `Debug` trait implementation generated by the macro allows formatted output with `println!`
    println!("struct is {:?}", demo);

    // Call the `double_foo()` method on `demo`
    // This method is generated by the macro and returns double the value of the `foo` field
    let double_foo = demo.double_foo();

    // Print the result of calling `double_foo` to the console
    println!("double foo: {}", double_foo);

    // let demo_2 = MyStruct2 { baz: 3, qux: 4 };
    // Does not compile because the struct is destroyed by the macro

    // println!("struct is {:?}", demo_2);

    let foo = Foo { bar: 3 };
    println!("{:?}", foo);
}
