[workspace]
members = ["programs/*"]
resolver = "2"

[profile.release]
# Let to true in general but false if high computation
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
